### ISSUE TITLE
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

### ISSUE THREAD

**Issue by lbdhr** [evg-dev/titanic-keras-nn#1]
**Fantastic Work!**

But I have got an error while I am running this code at `index = test["PassengerId"].as_matrix()`

The error information is "**IndexError: only integers, slices (\`:\`), ellipsis (\`...\`), numpy.newaxis (\`None\`) and integer or boolean arrays are valid indices**"

Looking forward to your favourable reply.

**Comment by evg-dev** [comment]
Oh, thank you. Fixed#1.
